name: 'swim_data_warehouse_dbt'
version: '1.0.0'
config-version: 2

profile: 'swim_data_warehouse_dbt'

clean-targets:
  - "target"

models:

  swim_data_warehouse_dbt:
    +materialized: table

    isl_dw:
      +schema: isl

    isl_hand_written:
      +schema: hand_written
      +materialized: ephemeral

    lenex:
      +schema: lenex
